services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-uv-app
    stdin_open: true
    tty: true

    ports:
      # Use environment variables for ports.
      # The :- syntax provides a default value if the variable isn't set.
      # You can set these in the Portainer UI when deploying the stack.
      - "8980:8000"
      - "8981:8081"
      - "8922:22"

    # The volumes section is now much simpler. We only need a volume
    # for data that must persist *between* container deployments.
    # The application code itself is now part of the image.
    volumes:
      - persistent_data:/persistent_data

    # The command is now to run the script we created inside the image.
    command: sh /app/startup.sh

volumes:
  persistent_data:
